# Generated by Django 6.0.7 on 2026-07-19 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_employeeprofile_employment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCurrentSalaryComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('special_allowence', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('house_rent_allowence', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('conveyance_allowence', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('phone_allowence', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('medical_allowence', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('deductions_EPF', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('deductions_ESI', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('deductions_TDS', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('deductions_professional_tax', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('deductions_other', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('employer_epf', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('employer_esi', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('total_allowence', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('gross_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('total_deductions', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('net_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('cost_to_company', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
