# Generated by Django 6.0.7 on 2026-07-19 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_employeeprofile_base_salary'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved (Awaiting Payout)'), ('PAID', 'Disbursed to Employee'), ('REJECTED', 'Rejected'), ('DEDUCTED', 'Fully Recovered from Salary')], default='PENDING', max_length=20)),
                ('disbursement_date', models.DateField(blank=True, help_text='When the owner gave the cash/transfer', null=True)),
                ('recovery_month', models.DateField(blank=True, help_text='The salary cycle month this should be deducted from (e.g., 2026-08-01)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlySalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('special_allowence', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('house_rent_allowence', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('conveyance_allowence', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('phone_allowence', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('medical_allowence', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('deductions_EPF', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('deductions_ESI', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('deductions_TDS', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('deductions_professional_tax', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('deductions_other', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('employer_epf', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('employer_esi', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('total_allowence', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('gross_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('total_deductions', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('net_salary', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('cost_to_company', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TRAVEL', 'Travel & Fuel Allowance'), ('FOOD', 'Food & Meals'), ('MEDICAL', 'Medical & Healthcare'), ('EQUIPMENT', 'Hardware & Equipment Procurement'), ('SOFTWARE', 'Software & SaaS Subscriptions'), ('RENT', 'Office Space & Storage Rent'), ('UTILITIES', 'Electricity & Water Utilities'), ('COMMUNICATION', 'Phone & Internet Allowance'), ('OFFICE_SUPPLIES', 'Office Stationery & Supplies'), ('LOGISTICS', 'Courier, Shipping & Delivery Costs'), ('MAINTENANCE', 'Office Repair & Maintenance'), ('CLIENT_MEETING', 'Client Entertainment & Hospitality'), ('MARKETING', 'Local Marketing & Business Ads'), ('TEAM_WELFARE', 'Team Celebrations & Snacks'), ('TRAINING', 'Courses, Books & Employee Training'), ('BONUS', 'Performance Bonus'), ('FESTIVAL_GIFT', 'Festival Incentive Token'), ('OTHER', 'Other Out-of-Pocket Expenses')], default='OTHER', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('PAID_WITH_PAYROLL', 'Settled via Monthly Salary Payout'), ('PAID_DIRECT', 'Paid Out Cache/Direct Transfer'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_processed_in_salary', models.BooleanField(default=False, help_text='Tells the payroll engine if this money was already returned to the employee')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
