# Generated by Django 6.0.7 on 2026-07-23 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_employeeprofile_base_salary'),
        ('payroll', '0002_advancepayment_monthlysalaryrecord_reimbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalaryrecord',
            name='advances_deducted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlysalaryrecord',
            name='approved_reimbursements',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlysalaryrecord',
            name='lop_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalaryrecord',
            name='lop_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlysalaryrecord',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'JANUARY'), (2, 'FEBUARY'), (3, 'MARCH'), (4, 'APRIL'), (5, 'MAY'), (6, 'JUNE'), (7, 'JULY'), (8, 'AUGUST'), (9, 'SEPTEMBER'), (10, 'OCTOBER'), (11, 'NOVEMBER'), (12, 'DECEMBER')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='monthlysalaryrecord',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='monthlysalaryrecord',
            name='year',
            field=models.IntegerField(blank=True, default=2026, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='monthlysalaryrecord',
            unique_together={('tenant', 'employee', 'month', 'year')},
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Holiday', 'Holiday'), ('Leave', 'Leave')], default='PENDING', max_length=20)),
                ('is_lop', models.BooleanField(default=False, help_text='Triggers salary deduction if True')),
                ('lop_override_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employeeprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organisation')),
            ],
            options={
                'unique_together': {('tenant', 'employee', 'date')},
            },
        ),
    ]
