# Generated by Django 6.0.7 on 2026-07-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_monthlysalaryrecord_advances_deducted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalaryrecord',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlysalaryrecord',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('BANK_TRANSFER', 'Bank Transfer')], default='BANK_TRANSFER', max_length=20, null=True),
        ),
    ]
