# Generated by Django 6.0.7 on 2026-07-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organisationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationprofile',
            name='org_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisationprofile',
            name='org_bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organisationprofile',
            name='org_base_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='organisationprofile',
            name='org_date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisationprofile',
            name='org_ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='organisationprofile',
            name='org_pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organisationprofile',
            name='org_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
