# Generated by Django 6.0.6 on 2026-07-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organisationprofile_org_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
