# Generated by Django 6.0.6 on 2026-07-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_employeeprofile_employment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='base_salary',
        ),
    ]
